FROM openjdk:17-alpine as base
RUN apk update && apk add --no-cache tzdata
ENV TZ=America/Sao_Paulo
RUN cp /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime
WORKDIR /app
EXPOSE 8080

FROM gradle:7.6.1-jdk17-alpine as build

WORKDIR /app

COPY buildSrc buildSrc
COPY feature feature
COPY lib lib
COPY gradle gradle
COPY src src
COPY build.gradle.kts build.gradle.kts
COPY gradlew gradlew
COPY gradlew.bat gradlew.bat
COPY settings.gradle.kts settings.gradle.kts
COPY --chown=gradle:gradle . /home/gradle

RUN gradle build || return 1

FROM base as final
COPY --from=build /app/build/libs/*.jar dexpay.jar

ENTRYPOINT ["java", "-jar", "dexpay.jar"]