spring:
  application:
    name: spring-webflux-api
#  webflux:
#    base-path: /api
  data:
    mongodb:
      authentication-database: admin
      uri: mongodb://admin-teste:Teste2020bd!@localhost:27017/Test?authSource=admin
      database: Test
      vault:
        uri: mongodb://admin-teste:Teste2020bd!@localhost:27017/Test?authSource=admin
      storage:
        uri: mongodb://admin-teste:Teste2020bd!@localhost:27017/Test?authSource=admin

mongodb:
  key:
    vault:
      db: encryption
      coll: keyVault
  kms:
    provider: local
  master:
    key:
      file:
        path: ./master-key.txt

crypt:
  shared:
    lib:
      path: ./mongo_crypt_shared_v1-windows-x86_64-enterprise-7.0.7/bin/mongo_crypt_v1

springdoc:
  swagger-ui:
    enabled: true
    path: /v1/swagger-ui.html
  api-docs:
    path: /v1/finapp-docs

server:
  port: 8080

logging:
  level:
    io:
      reflectoring: DEBUG
    org:
      springframework:
        web: INFO
        data:
          mongodb:
            core:
              ReactiveMongoTemplate: DEBUG
    reactor:
      netty:
        http:
          client: DEBUG

finapp:
  jwt:
    secret: "4etFgqnKUn7REKMfS2DHWiJa3nLtRUpj9tsH9ig9iFWhm6FfmJxw90QMlv3VioW"
    expirationMs: "259200"
