ACCESS_TOKEN_PRIVATE_KEY_PATH: "access-refresh-token-keys/access-token-private.key"
ACCESS_TOKEN_PUBLIC_KEY_PATH: "access-refresh-token-keys/access-token-public.key"
REFRESH_TOKEN_PRIVATE_KEY_PATH: "access-refresh-token-keys/refresh-token-private.key"
REFRESH_TOKEN_PUBLIC_KEY_PATH: "access-refresh-token-keys/refresh-token-public.key"

spring:
  cloud:
    stream:
      bindings:
        consumeMessage-in-0:
          destination: "${kafka.topic.product}"
          binder: kafka
          group: product-consumer-group
        produceMessage-out-0:
          destination: "${kafka.topic.product}"
          binder: kafka
        enrichAndSendToRabbit-in-0:
          destination: "${kafka.topic.product}"
          binder: kafka
          group: product-enrich-group
        enrichAndSendToRabbit-out-0:
          destination: "${kafka.topic.multiName}"
          binder: kafka
        multiInMultiOut-in-0:
          destination: "${kafka.topic.multiName}"
          binder: kafka
          group: product-multimessage-group
        multiInMultiOut-in-1:
          destination: "${kafka.topic.product}"
          binder: kafka
          group: product-multimessage-group
        multiInMultiOut-out-0:
          destination: "${kafka.topic.multiNameOut}"
        multiInMultiOut-out-1:
          destination: "${kafka.topic.multiQuantity}"
      kafka:
        default:
          producer:
            recordMetadataChannel: producerMetadata
        bindings:
          consumeMessage-in-0:
            enableDlq: true