spring:
  application:
    name: spring-webflux-api
#  webflux:
#    base-path: /api
  data:
    mongodb:
      authentication-database: admin
      uri: mongodb://admin-teste:Teste2020bd!@localhost:27017/Test?authSource=admin
      database: Test

logging:
  level:
    io:
      reflectoring: DEBUG
    org:
      springframework:
        web: INFO
        data:
          mongodb:
            core:
              ReactiveMongoTemplate: DEBUG
    reactor:
      netty:
        http:
          client: DEBUG

finapp:
  jwt:
    secret: "4etFgqnKUn7REKMfS2DHWiJa3nLtRUpj9tsH9ig9iFWhm6FfmJxw90QMlv3VioW"
    expirationMs: "259200"
