access-token:
  private: ${ACCESS_TOKEN_PRIVATE_KEY_PATH}
  public: ${ACCESS_TOKEN_PUBLIC_KEY_PATH}
refresh-token:
  private: ${REFRESH_TOKEN_PRIVATE_KEY_PATH}
  public: ${REFRESH_TOKEN_PUBLIC_KEY_PATH}

server:
  port: 8080

kafka:
  brokers: localhost:9092
  topic:
    product: product-topic
    multiNameOut: multi-name-topic-out
    multiName: multi-name-topic
    multiQuantity: multi-quantity-topic

spring:
  profiles:
    include:
      - cloudstream
  data:
    mongodb:
      authentication-database: admin
      uri: mongodb://admin-teste:Teste2020bd!@localhost:27017/Test?authSource=admin
      database: Test
      vault:
        uri: mongodb://admin-teste:Teste2020bd!@localhost:27017/Test?authSource=admin
      storage:
        uri: mongodb://admin-teste:Teste2020bd!@localhost:27017/Test?authSource=admin

  application:
    name: spring-webflux-api

  kafka:
    bootstrap-servers: ${kafka.brokers}
    consumer:
      properties:
        spring.json.trusted.packages: "*"

  cloud:
    function:
      definition: consumeMessage;produceMessage;enrichAndSendToRabbit;multiInMultiOut
    stream:
      default-binder: kafka
      kafka:
        binder:
          auto-create-topics: true
          consumer-properties:
            key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value.deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            max.poll.records: 10
            spring.json.trusted.packages: "*"
          producer-properties:
            key.serializer: org.apache.kafka.common.serialization.StringSerializer
            value.serializer: org.springframework.kafka.support.serializer.JsonSerializer

mongodb:
  key:
    vault:
      db: encryption
      coll: keyVault
  kms:
    provider: local
  master:
    key:
      file:
        path: ./master-key.txt

crypt:
  shared:
    lib:
      path: ./mongo_crypt_shared_v1-windows-x86_64-enterprise-7.0.7/bin/mongo_crypt_v1

springdoc:
  swagger-ui:
    enabled: true
    path: /v1/swagger-ui.html
  api-docs:
    path: /v1/finapp-docs

logging:
  level:
    io:
      reflectoring: DEBUG
    org:
      springframework:
        web: INFO
        data:
          mongodb:
            core:
              ReactiveMongoTemplate: DEBUG
    reactor:
      netty:
        http:
          client: DEBUG
